#ifndef SPECIAL_H_
#define SPECIAL_H_

#include "ADD.h"
#include "ADDU.h"
#include "AND.h"
#include "BREAK.h"
#include "CLO.h"
#include "CLZ.h"
#include "DIV.h"
#include "DIVU.h"
#include "NOP.h"
#include "NOR.h"
#include "JALR.h"
#include "JR.h"
#include "MADD.h"
#include "MADDU.h"
#include "MAX.h"
#include "MFHI.h"
#include "MFLO.h"
#include "MIN.h"
#include "MOVN.h"
#include "MOVZ.h"
#include "MSUB.h"
#include "MSUBU.h"
#include "MTHI.h"
#include "MTLO.h"
#include "MULT.h"
#include "MULTU.h"
#include "OR.h"
#include "ROTR.h"
#include "ROTRV.h"
#include "SLL.h"
#include "SLLV.h"
#include "SLT.h"
#include "SLTU.h"
#include "SRA.h"
#include "SRAV.h"
#include "SRL.h"
#include "SRLV.h"
#include "SUB.h"
#include "SUBU.h"
#include "SYSCALL.h"
#include "XOR.h"

#endif

