#ifndef BASIC_H_
#define BASIC_H_
#pragma once

#include "ADDI.h"
#include "ADDIU.h"
#include "ANDI.h"
#include "BEQ.h"
#include "BEQL.h"
#include "BGTZ.h"
#include "BGTZL.h"
#include "BLEZ.h"
#include "BLEZL.h"
#include "BNE.h"
#include "BNEL.h"
#include "CACHE.h"
#include "J.h"
#include "JAL.h"
#include "LB.h"
#include "LBU.h"
#include "LH.h"
#include "LHU.h"
#include "LUI.h"
#include "LW.h"
#include "LWL.h"
#include "LWC1.h"
#include "ORI.h"
#include "SB.h"
#include "SH.h"
#include "SW.h"
#include "SLTI.h"
#include "SLTIU.h"
#include "XORI.h"

#endif
